import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Air Jordan 1 Retro High OG',
    brand: 'Jordan',
    category: 'Кроссовки',
    price: 2200000,
    originalPrice: 2800000,
    image: '/products/jordan1-chicago.jpg',
    images: ['/products/jordan1-chicago.jpg'],
    colorway: 'Chicago / Red White Black',
    sku: 'DKN-555088-101',
    year: 2023,
    verified: true,
    badge: 'TRENDING',
    description: 'Air Jordan 1 Retro High OG "Chicago" — классика уличной культуры. Оригинальная цветовая гамма 1985 года, переосмысленная для современного поколения. Каждая пара верифицирована командой DUCANI.',
    sizes: [
      { size: '38', available: true },
      { size: '39', available: true },
      { size: '40', available: false },
      { size: '41', available: true },
      { size: '42', available: true },
      { size: '43', available: true },
      { size: '44', available: false },
      { size: '45', available: true },
    ],
  },
  {
    id: '2',
    name: 'Nike Dunk Low',
    brand: 'Nike',
    category: 'Кроссовки',
    price: 1900000,
    image: '/products/dunk-panda.jpg',
    images: ['/products/dunk-panda.jpg'],
    colorway: 'Panda / White Black',
    sku: 'DKN-DD1391-100',
    year: 2023,
    verified: true,
    badge: 'NEW',
    description: 'Nike Dunk Low "Panda" — самая популярная модель последних лет. Минималистичный дизайн в бело-чёрной гамме. Универсальна — подходит к любому образу.',
    sizes: [
      { size: '38', available: true },
      { size: '39', available: true },
      { size: '40', available: true },
      { size: '41', available: true },
      { size: '42', available: true },
      { size: '43', available: false },
      { size: '44', available: true },
      { size: '45', available: true },
    ],
  },
  {
    id: '3',
    name: 'Nike Air Force 1 Low',
    brand: 'Nike',
    category: 'Кроссовки',
    price: 1400000,
    image: '/products/af1-white.jpg',
    images: ['/products/af1-white.jpg'],
    colorway: 'Triple White',
    sku: 'DKN-315122-111',
    year: 2024,
    verified: true,
    description: 'Nike Air Force 1 Low — легендарная модель с 1982 года. Полностью белый дизайн, премиальная кожа, непревзойдённый комфорт. Основа любого гардероба.',
    sizes: [
      { size: '38', available: true },
      { size: '39', available: false },
      { size: '40', available: true },
      { size: '41', available: true },
      { size: '42', available: true },
      { size: '43', available: true },
      { size: '44', available: true },
      { size: '45', available: false },
    ],
  },
  {
    id: '4',
    name: 'Air Jordan 4 Retro',
    brand: 'Jordan',
    category: 'Кроссовки',
    price: 2800000,
    image: '/products/jordan4-military.jpg',
    images: ['/products/jordan4-military.jpg'],
    colorway: 'Military Black',
    sku: 'DKN-DH7138-006',
    year: 2022,
    verified: true,
    badge: 'RARE',
    description: 'Air Jordan 4 "Military Black" — один из самых желанных релизов. Чёрный замшевый верх с культовой сеткой. Ограниченный тираж — не упусти.',
    sizes: [
      { size: '39', available: true },
      { size: '40', available: true },
      { size: '41', available: false },
      { size: '42', available: true },
      { size: '43', available: true },
      { size: '44', available: false },
      { size: '45', available: true },
    ],
  },
  {
    id: '5',
    name: 'New Balance 550',
    brand: 'New Balance',
    category: 'Кроссовки',
    price: 1600000,
    image: '/products/nb550-green.jpg',
    images: ['/products/nb550-green.jpg'],
    colorway: 'White Green',
    sku: 'DKN-BB550WT1',
    year: 2023,
    verified: true,
    badge: 'NEW',
    description: 'New Balance 550 — ретро-силуэт из 80-х вернулся в моду. Кожаный верх, классический дизайн. Идеально для тех, кто ценит историю и стиль.',
    sizes: [
      { size: '38', available: true },
      { size: '39', available: true },
      { size: '40', available: true },
      { size: '41', available: true },
      { size: '42', available: false },
      { size: '43', available: true },
      { size: '44', available: true },
      { size: '45', available: true },
    ],
  },
  {
    id: '6',
    name: 'Adidas Samba OG',
    brand: 'Adidas',
    category: 'Кроссовки',
    price: 1450000,
    image: '/products/samba-white.jpg',
    images: ['/products/samba-white.jpg'],
    colorway: 'White / Core Black',
    sku: 'DKN-B75806',
    year: 2024,
    verified: true,
    description: 'Adidas Samba OG — культовая футбольная модель 1950 года стала символом уличной моды. Гумовая подошва, замшевые вставки, классический дизайн.',
    sizes: [
      { size: '38', available: false },
      { size: '39', available: true },
      { size: '40', available: true },
      { size: '41', available: true },
      { size: '42', available: true },
      { size: '43', available: true },
      { size: '44', available: false },
      { size: '45', available: true },
    ],
  },
  {
    id: '7',
    name: 'Travis Scott x Jordan 1 Low',
    brand: 'Jordan',
    category: 'Кроссовки',
    price: 8500000,
    image: '/products/ts-jordan-low.jpg',
    images: ['/products/ts-jordan-low.jpg'],
    colorway: 'Reverse Mocha',
    sku: 'DKN-DN2487-200',
    year: 2022,
    verified: true,
    badge: 'RARE',
    description: 'Travis Scott x Air Jordan 1 Low "Reverse Mocha" — одна из самых эксклюзивных коллабораций. Перевёрнутый Swoosh, замшевый верх, стелька с портретом. Редчайший экземпляр.',
    sizes: [
      { size: '40', available: true },
      { size: '41', available: true },
      { size: '42', available: true },
      { size: '43', available: false },
      { size: '44', available: true },
    ],
  },
  {
    id: '8',
    name: 'Yeezy Boost 350 V2',
    brand: 'Yeezy',
    category: 'Кроссовки',
    price: 2600000,
    originalPrice: 3100000,
    image: '/products/yeezy-zebra.jpg',
    images: ['/products/yeezy-zebra.jpg'],
    colorway: 'Zebra / White Red',
    sku: 'DKN-CP9654',
    year: 2022,
    verified: true,
    badge: 'SALE',
    description: 'Yeezy Boost 350 V2 "Zebra" — один из самых иконичных силуэтов Kanye West. Primeknit верх, технология Boost для максимального комфорта.',
    sizes: [
      { size: '38', available: true },
      { size: '39', available: true },
      { size: '40', available: true },
      { size: '41', available: false },
      { size: '42', available: true },
      { size: '43', available: true },
      { size: '44', available: true },
      { size: '45', available: false },
    ],
  },
];

export const BRANDS = ['Nike', 'Jordan', 'Adidas', 'New Balance', 'Yeezy'];
export const CATEGORIES = ['Кроссовки', 'Одежда', 'Аксессуары'];
export const SIZES = ['38', '39', '40', '41', '42', '43', '44', '45'];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('ru-UZ').format(price) + ' UZS';
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
